;;; Copyright (c) 2012-2014, Alvaro Castro-Castilla. All rights reserved.
;;; Non-standard list procedures

(##namespace ("fabric:algorithm/list-extra#"
              atom?
              xor
              snoc
              uncons
              uncons-2
              uncons-3
              uncons-4
              uncons-cons
              unlist
              list->values
              unvector
              vector->values
              cars+cdrs
              cars
              cdrs
              list-swap
              map*
              map**
              map/values
              fold/values
              demux
              pair-map
              map+fold
              pair-fold-x
              pair-fold-2
              intersperse
              remove-first
              remove-any
              remove-every
              find-remove
              find+remove
              find-rotate
              most
              most+remove
              most/generator
              max/generator
              min/generator
              x-substitute
              substitute-first
              substitute
              x-subst*
              substitute-first*
              substitute*
              flatten
              flatten-unordered
              list->skeleton
              expand-skeleton
              apply-skeleton
              slice
              slice!
              split-in-halves
              split-in-halves!
              case-classify
              ticker!))
